---
title: Dimensionner des éléments par rapport à la taille de la fenêtre d'affichage
hero_image: images/banner.png
description: Dimensionner des éléments par rapport à la taille de la fenêtre d'affichage
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Dimensionner des éléments par rapport à la taille de la fenêtre d'affichage
